# Exploratory Data Analysis

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
file_path = "./DataSets/"
training_data = pd.read_csv(file_path + 'counterfeit_train.csv')
production_data = pd.read_csv(file_path + 'counterfeit_test.csv')

In [3]:
training_data.head()

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales
0,RRA15,13.100,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026
1,YVV26,NaN,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520
2,LJC15,9.025,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920
3,GWC40,11.800,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130
4,QMN13,NaN,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402

In [25]:
production_data.head()

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level
0,HLZ81,NaN,Area027,1983,85.5328,Antibiotics,mild,0.112747,CityLimits,Tier 3,Medium
1,ECE94,13.45,Area045,2000,257.1460,OralContraceptives,mild,0.144446,DownTown,Tier 2,Unknown
2,SAD14,7.10,Area045,2000,98.1172,Antipyretics,mild,0.144221,DownTown,Tier 2,Unknown
3,EQV63,18.30,Area010,1996,135.3730,Tranquilizers,mild,0.100388,MidTownResidential,Tier 3,Unknown
4,AIR10,NaN,Area019,1983,112.8016,OralContraceptives,mild,0.022585,MidTownResidential,Tier 1,Small

In [26]:
training_data['Counterfeit_Weight'].mean()

14.115056617126996

In [27]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818 entries, 0 to 6817
Data columns (total 12 columns):
Medicine_ID            6818 non-null object
Counterfeit_Weight     5652 non-null float64
DistArea_ID            6818 non-null object
Active_Since           6818 non-null int64
Medicine_MRP           6818 non-null float64
Medicine_Type          6818 non-null object
SidEffect_Level        6818 non-null object
Availability_rating    6818 non-null float64
Area_Type              6818 non-null object
Area_City_Type         6818 non-null object
Area_dist_level        6818 non-null object
Counterfeit_Sales      6818 non-null float64
dtypes: float64(4), int64(1), object(7)
memory usage: 639.3+ KB

In [28]:
production_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
Medicine_ID            1705 non-null object
Counterfeit_Weight     1408 non-null float64
DistArea_ID            1705 non-null object
Active_Since           1705 non-null int64
Medicine_MRP           1705 non-null float64
Medicine_Type          1705 non-null object
SidEffect_Level        1705 non-null object
Availability_rating    1705 non-null float64
Area_Type              1705 non-null object
Area_City_Type         1705 non-null object
Area_dist_level        1705 non-null object
dtypes: float64(3), int64(1), object(7)
memory usage: 146.6+ KB

Creating a Dummy sales variable in the production data and combining it with training data for further data manipulations

In [31]:
production_data['Counterfeit_Sales'] = np.NAN

In [34]:
training_data['Data_from'] = 'Train'
production_data['Data_from'] = 'Production'

In [35]:
full_data = pd.concat([training_data,production_data],axis=0)

In [42]:
full_data.loc[full_data['Data_from'] == 'Train',]

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales,Data_from
0,RRA15,13.100,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026,Train
1,YVV26,NaN,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520,Train
2,LJC15,9.025,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920,Train
3,GWC40,11.800,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130,Train
4,QMN13,NaN,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402,Train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6813,OYN80,8.535,Area046,1995,204.1452,Hreplacements,mild,0.112963,DownTown,Tier 1,Small,2070.4520,Train
6814,ACW12,20.650,Area046,1995,235.1088,Hreplacements,mild,0.131103,DownTown,Tier 1,Small,2126.3792,Train
6815,OPM10,20.000,Area017,2005,193.6292,Antimalarial,critical,0.105096,DownTown,Tier 2,Unknown,2119.7212,Train
6816,SLY12,10.180,Area045,2000,162.8682,Statins,mild,0.099957,DownTown,Tier 2,Unknown,1485.2138,Train
6817,ATT10,7.930,Area018,2007,177.5500,Mstablizers,critical,0.117445,Industrial,Tier 3,Medium,1943.9500,Train

In [53]:
full_data['DistArea_ID'].value_counts()

Area027    935
Area013    932
Area046    930
Area049    930
Area035    930
Area045    929
Area018    928
Area017    926
Area010    555
Area019    528
Name: DistArea_ID, dtype: int64

In [54]:
full_data['Area_Type'].value_counts()

DownTown              5577
MidTownResidential    1083
CityLimits             935
Industrial             928
Name: Area_Type, dtype: int64

In [63]:
full_data.loc[full_data['Area_Type']=='DownTown','DistArea_ID'].unique()

array(['Area046', 'Area045', 'Area013', 'Area017', 'Area035', 'Area049'],
      dtype=object)

In [65]:
full_data.loc[full_data['Area_Type']=='MidTownResidential','DistArea_ID'].unique()

array(['Area019', 'Area010'], dtype=object)

In [66]:
full_data.loc[full_data['Area_Type']=='CityLimits','DistArea_ID'].unique()

array(['Area027'], dtype=object)

In [67]:
full_data.loc[full_data['Area_Type']=='Industrial','DistArea_ID'].unique()

array(['Area018'], dtype=object)

In [68]:
full_data.head()

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales,Data_from
0,RRA15,13.100,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026,Train
1,YVV26,NaN,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520,Train
2,LJC15,9.025,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920,Train
3,GWC40,11.800,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130,Train
4,QMN13,NaN,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402,Train

In [69]:
full_data['Medicine_Type'].value_counts()

Antibiotics           1232
Hreplacements         1200
Antiseptics            910
OralContraceptives     856
Antipyretics           682
Cardiac                649
Mstablizers            648
Tranquilizers          520
Analgesics             445
Antimalarial           425
Antacids               251
Statins                214
MuscleRelaxants        169
Antifungal             148
Stimulants             110
Antiviral               64
Name: Medicine_Type, dtype: int64

In [72]:
round(full_data.groupby('Medicine_Type')['Counterfeit_Sales'].mean(),2)

Medicine_Type
Analgesics            2091.24
Antacids              2259.88
Antibiotics           2397.20
Antifungal            2444.06
Antimalarial          2192.68
Antipyretics          2292.72
Antiseptics           2366.59
Antiviral             2583.16
Cardiac               2362.98
Hreplacements         2376.12
Mstablizers           2044.87
MuscleRelaxants       2091.09
OralContraceptives    2245.22
Statins               2309.45
Stimulants            2279.97
Tranquilizers         2084.45
Name: Counterfeit_Sales, dtype: float64

In [73]:
full_data['SidEffect_Level'].value_counts()

mild        5517
critical    3006
Name: SidEffect_Level, dtype: int64

In [74]:
full_data['Area_dist_level'].value_counts()

Medium     2793
Unknown    2410
Small      2388
High        932
Name: Area_dist_level, dtype: int64

#### After looking into all the categorical  variables, we cannot drop them and we create dummies for each variable for simplicity later we can ckeck for additional options to improve the performance

In [75]:
full_data.head(10)

,Medicine_ID,Counterfeit_Weight,DistArea_ID,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales,Data_from
0,RRA15,13.100,Area046,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,1775.5026,Train
1,YVV26,NaN,Area027,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520,Train
2,LJC15,9.025,Area046,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,2603.0920,Train
3,GWC40,11.800,Area046,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,1101.7130,Train
4,QMN13,NaN,Area019,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402,Train
5,JDG81,8.775,Area045,2000,165.5656,Antiseptics,mild,0.088881,DownTown,Tier 2,Unknown,3047.8464,Train
6,KPX48,18.000,Area018,2007,156.9102,Hreplacements,critical,0.051685,Industrial,Tier 3,Medium,2883.3938,Train
7,CYW14,7.680,Area013,1985,154.3470,Antiseptics,mild,0.028150,DownTown,Tier 3,High,3262.2340,Train
8,TVF57,18.550,Area046,1995,107.3068,Hreplacements,critical,0.060266,DownTown,Tier 1,Small,1959.9292,Train
9,MGU75,9.510,Area013,1985,161.1392,Statins,mild,0.023755,DownTown,Tier 3,High,3095.7840,Train

In [76]:
d = pd.get_dummies(full_data['DistArea_ID'],prefix='DistID',drop_first=True)

In [78]:
full_data = pd.concat((full_data,d),axis='columns')

In [79]:
full_data.drop('DistArea_ID',axis='columns',inplace=True)

In [80]:
full_data

,Medicine_ID,Counterfeit_Weight,Active_Since,Medicine_MRP,Medicine_Type,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,...,Data_from,DistID_Area013,DistID_Area017,DistID_Area018,DistID_Area019,DistID_Area027,DistID_Area035,DistID_Area045,DistID_Area046,DistID_Area049
0,RRA15,13.100,1995,160.2366,Antimalarial,critical,0.070422,DownTown,Tier 1,Small,...,Train,0,0,0,0,0,0,0,1,0
1,YVV26,NaN,1983,110.4384,Mstablizers,mild,0.013000,CityLimits,Tier 3,Medium,...,Train,0,0,0,0,1,0,0,0,0
2,LJC15,9.025,1995,259.4092,Cardiac,mild,0.060783,DownTown,Tier 1,Small,...,Train,0,0,0,0,0,0,0,1,0
3,GWC40,11.800,1995,99.9830,OralContraceptives,mild,0.065555,DownTown,Tier 1,Small,...,Train,0,0,0,0,0,0,0,1,0
4,QMN13,NaN,1983,56.4402,Hreplacements,critical,0.248859,MidTownResidential,Tier 1,Small,...,Train,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,KXW10,NaN,1983,136.5704,Hreplacements,mild,0.050505,CityLimits,Tier 3,Medium,...,Production,0,0,0,0,1,0,0,0,0
1701,CKE54,21.300,2002,57.0744,Antibiotics,critical,0.041118,DownTown,Tier 2,Small,...,Production,0,0,0,0,0,1,0,0,0
1702,HAY13,20.400,2005,182.7422,Antiseptics,mild,0.191273,DownTown,Tier 2,Unknown,...,Production,0,1,0,0,0,0,0,0,0
1703,ZEE32,20.000,2007,266.9672,Hreplacements,mild,0.013000,Industrial,Tier 3,Medium,...,Production,0,0,1,0,0,0,0,0,0
1704,NDL93,8.080,2000,238.7694,Antibiotics,critical,0.098982,DownTown,Tier 2,Unknown,...,Production,0,0,0,0,0,0,1,0,0

##### Medicine variable - Dummy Creations

In [81]:
d = pd.get_dummies(full_data['Medicine_Type'],prefix='MedType',drop_first=True)
full_data = pd.concat((full_data,d),axis='columns')
full_data.drop('Medicine_Type',axis='columns',inplace=True,)

In [82]:
full_data

,Medicine_ID,Counterfeit_Weight,Active_Since,Medicine_MRP,SidEffect_Level,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales,...,MedType_Antiseptics,MedType_Antiviral,MedType_Cardiac,MedType_Hreplacements,MedType_Mstablizers,MedType_MuscleRelaxants,MedType_OralContraceptives,MedType_Statins,MedType_Stimulants,MedType_Tranquilizers
0,RRA15,13.100,1995,160.2366,critical,0.070422,DownTown,Tier 1,Small,1775.5026,...,0,0,0,0,0,0,0,0,0,0
1,YVV26,NaN,1983,110.4384,mild,0.013000,CityLimits,Tier 3,Medium,3069.1520,...,0,0,0,0,1,0,0,0,0,0
2,LJC15,9.025,1995,259.4092,mild,0.060783,DownTown,Tier 1,Small,2603.0920,...,0,0,1,0,0,0,0,0,0,0
3,GWC40,11.800,1995,99.9830,mild,0.065555,DownTown,Tier 1,Small,1101.7130,...,0,0,0,0,0,0,1,0,0,0
4,QMN13,NaN,1983,56.4402,critical,0.248859,MidTownResidential,Tier 1,Small,158.9402,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,KXW10,NaN,1983,136.5704,mild,0.050505,CityLimits,Tier 3,Medium,NaN,...,0,0,0,1,0,0,0,0,0,0
1701,CKE54,21.300,2002,57.0744,critical,0.041118,DownTown,Tier 2,Small,NaN,...,0,0,0,0,0,0,0,0,0,0
1702,HAY13,20.400,2005,182.7422,mild,0.191273,DownTown,Tier 2,Unknown,NaN,...,1,0,0,0,0,0,0,0,0,0
1703,ZEE32,20.000,2007,266.9672,mild,0.013000,Industrial,Tier 3,Medium,NaN,...,0,0,0,1,0,0,0,0,0,0
1704,NDL93,8.080,2000,238.7694,critical,0.098982,DownTown,Tier 2,Unknown,NaN,...,0,0,0,0,0,0,0,0,0,0

##### SidEffect_Level - Dummy Creation

In [84]:
full_data['SidEffect_Level'].value_counts()

mild        5517
critical    3006
Name: SidEffect_Level, dtype: int64

In [87]:
d = pd.get_dummies(full_data['SidEffect_Level'],prefix='SidLvl',drop_first=True)
full_data = pd.concat((full_data,d),axis='columns')
full_data.drop('SidEffect_Level',axis='columns',inplace = True)

In [88]:
full_data

,Medicine_ID,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,Area_Type,Area_City_Type,Area_dist_level,Counterfeit_Sales,Data_from,...,MedType_Antiviral,MedType_Cardiac,MedType_Hreplacements,MedType_Mstablizers,MedType_MuscleRelaxants,MedType_OralContraceptives,MedType_Statins,MedType_Stimulants,MedType_Tranquilizers,SidLvl_mild
0,RRA15,13.100,1995,160.2366,0.070422,DownTown,Tier 1,Small,1775.5026,Train,...,0,0,0,0,0,0,0,0,0,0
1,YVV26,NaN,1983,110.4384,0.013000,CityLimits,Tier 3,Medium,3069.1520,Train,...,0,0,0,1,0,0,0,0,0,1
2,LJC15,9.025,1995,259.4092,0.060783,DownTown,Tier 1,Small,2603.0920,Train,...,0,1,0,0,0,0,0,0,0,1
3,GWC40,11.800,1995,99.9830,0.065555,DownTown,Tier 1,Small,1101.7130,Train,...,0,0,0,0,0,1,0,0,0,1
4,QMN13,NaN,1983,56.4402,0.248859,MidTownResidential,Tier 1,Small,158.9402,Train,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,KXW10,NaN,1983,136.5704,0.050505,CityLimits,Tier 3,Medium,NaN,Production,...,0,0,1,0,0,0,0,0,0,1
1701,CKE54,21.300,2002,57.0744,0.041118,DownTown,Tier 2,Small,NaN,Production,...,0,0,0,0,0,0,0,0,0,0
1702,HAY13,20.400,2005,182.7422,0.191273,DownTown,Tier 2,Unknown,NaN,Production,...,0,0,0,0,0,0,0,0,0,1
1703,ZEE32,20.000,2007,266.9672,0.013000,Industrial,Tier 3,Medium,NaN,Production,...,0,0,1,0,0,0,0,0,0,1
1704,NDL93,8.080,2000,238.7694,0.098982,DownTown,Tier 2,Unknown,NaN,Production,...,0,0,0,0,0,0,0,0,0,0

##### Area_Type - Dummy Creation

In [89]:
d = pd.get_dummies(full_data['Area_Type'],prefix='ArTyp',drop_first=True)
full_data = pd.concat((full_data,d),axis='columns')
full_data.drop('Area_Type',axis='columns',inplace = True)

In [90]:
full_data

,Medicine_ID,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,Area_City_Type,Area_dist_level,Counterfeit_Sales,Data_from,DistID_Area013,...,MedType_Mstablizers,MedType_MuscleRelaxants,MedType_OralContraceptives,MedType_Statins,MedType_Stimulants,MedType_Tranquilizers,SidLvl_mild,ArTyp_DownTown,ArTyp_Industrial,ArTyp_MidTownResidential
0,RRA15,13.100,1995,160.2366,0.070422,Tier 1,Small,1775.5026,Train,0,...,0,0,0,0,0,0,0,1,0,0
1,YVV26,NaN,1983,110.4384,0.013000,Tier 3,Medium,3069.1520,Train,0,...,1,0,0,0,0,0,1,0,0,0
2,LJC15,9.025,1995,259.4092,0.060783,Tier 1,Small,2603.0920,Train,0,...,0,0,0,0,0,0,1,1,0,0
3,GWC40,11.800,1995,99.9830,0.065555,Tier 1,Small,1101.7130,Train,0,...,0,0,1,0,0,0,1,1,0,0
4,QMN13,NaN,1983,56.4402,0.248859,Tier 1,Small,158.9402,Train,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,KXW10,NaN,1983,136.5704,0.050505,Tier 3,Medium,NaN,Production,0,...,0,0,0,0,0,0,1,0,0,0
1701,CKE54,21.300,2002,57.0744,0.041118,Tier 2,Small,NaN,Production,0,...,0,0,0,0,0,0,0,1,0,0
1702,HAY13,20.400,2005,182.7422,0.191273,Tier 2,Unknown,NaN,Production,0,...,0,0,0,0,0,0,1,1,0,0
1703,ZEE32,20.000,2007,266.9672,0.013000,Tier 3,Medium,NaN,Production,0,...,0,0,0,0,0,0,1,0,1,0
1704,NDL93,8.080,2000,238.7694,0.098982,Tier 2,Unknown,NaN,Production,0,...,0,0,0,0,0,0,0,1,0,0

##### Area_dist_level - Dummy Creation

In [91]:
d = pd.get_dummies(full_data['Area_dist_level'],prefix='ArDisTyp',drop_first=True)
full_data = pd.concat((full_data,d),axis='columns')
full_data.drop('Area_dist_level',axis='columns',inplace = True)

In [92]:
full_data

,Medicine_ID,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,Area_City_Type,Counterfeit_Sales,Data_from,DistID_Area013,DistID_Area017,...,MedType_Statins,MedType_Stimulants,MedType_Tranquilizers,SidLvl_mild,ArTyp_DownTown,ArTyp_Industrial,ArTyp_MidTownResidential,ArDisTyp_Medium,ArDisTyp_Small,ArDisTyp_Unknown
0,RRA15,13.100,1995,160.2366,0.070422,Tier 1,1775.5026,Train,0,0,...,0,0,0,0,1,0,0,0,1,0
1,YVV26,NaN,1983,110.4384,0.013000,Tier 3,3069.1520,Train,0,0,...,0,0,0,1,0,0,0,1,0,0
2,LJC15,9.025,1995,259.4092,0.060783,Tier 1,2603.0920,Train,0,0,...,0,0,0,1,1,0,0,0,1,0
3,GWC40,11.800,1995,99.9830,0.065555,Tier 1,1101.7130,Train,0,0,...,0,0,0,1,1,0,0,0,1,0
4,QMN13,NaN,1983,56.4402,0.248859,Tier 1,158.9402,Train,0,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,KXW10,NaN,1983,136.5704,0.050505,Tier 3,NaN,Production,0,0,...,0,0,0,1,0,0,0,1,0,0
1701,CKE54,21.300,2002,57.0744,0.041118,Tier 2,NaN,Production,0,0,...,0,0,0,0,1,0,0,0,1,0
1702,HAY13,20.400,2005,182.7422,0.191273,Tier 2,NaN,Production,0,1,...,0,0,0,1,1,0,0,0,0,1
1703,ZEE32,20.000,2007,266.9672,0.013000,Tier 3,NaN,Production,0,0,...,0,0,0,1,0,1,0,1,0,0
1704,NDL93,8.080,2000,238.7694,0.098982,Tier 2,NaN,Production,0,0,...,0,0,0,0,1,0,0,0,0,1

##### Area_City_Type 	- Dummy Creation

In [94]:
d = pd.get_dummies(full_data['Area_City_Type'],prefix='ArCtyTyp',drop_first=True)
full_data = pd.concat((full_data,d),axis='columns')
full_data.drop('Area_City_Type',axis='columns',inplace = True)

In [95]:
full_data

,Medicine_ID,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,Counterfeit_Sales,Data_from,DistID_Area013,DistID_Area017,DistID_Area018,...,MedType_Tranquilizers,SidLvl_mild,ArTyp_DownTown,ArTyp_Industrial,ArTyp_MidTownResidential,ArDisTyp_Medium,ArDisTyp_Small,ArDisTyp_Unknown,ArCtyTyp_Tier 2,ArCtyTyp_Tier 3
0,RRA15,13.100,1995,160.2366,0.070422,1775.5026,Train,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1,YVV26,NaN,1983,110.4384,0.013000,3069.1520,Train,0,0,0,...,0,1,0,0,0,1,0,0,0,1
2,LJC15,9.025,1995,259.4092,0.060783,2603.0920,Train,0,0,0,...,0,1,1,0,0,0,1,0,0,0
3,GWC40,11.800,1995,99.9830,0.065555,1101.7130,Train,0,0,0,...,0,1,1,0,0,0,1,0,0,0
4,QMN13,NaN,1983,56.4402,0.248859,158.9402,Train,0,0,0,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,KXW10,NaN,1983,136.5704,0.050505,NaN,Production,0,0,0,...,0,1,0,0,0,1,0,0,0,1
1701,CKE54,21.300,2002,57.0744,0.041118,NaN,Production,0,0,0,...,0,0,1,0,0,0,1,0,1,0
1702,HAY13,20.400,2005,182.7422,0.191273,NaN,Production,0,1,0,...,0,1,1,0,0,0,0,1,1,0
1703,ZEE32,20.000,2007,266.9672,0.013000,NaN,Production,0,0,1,...,0,1,0,1,0,1,0,0,0,1
1704,NDL93,8.080,2000,238.7694,0.098982,NaN,Production,0,0,0,...,0,0,1,0,0,0,0,1,1,0

##### Dropping Medicine ID

In [96]:
full_data.drop('Medicine_ID',axis='columns',inplace=True)

In [97]:
full_data

,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,Counterfeit_Sales,Data_from,DistID_Area013,DistID_Area017,DistID_Area018,DistID_Area019,...,MedType_Tranquilizers,SidLvl_mild,ArTyp_DownTown,ArTyp_Industrial,ArTyp_MidTownResidential,ArDisTyp_Medium,ArDisTyp_Small,ArDisTyp_Unknown,ArCtyTyp_Tier 2,ArCtyTyp_Tier 3
0,13.100,1995,160.2366,0.070422,1775.5026,Train,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1,NaN,1983,110.4384,0.013000,3069.1520,Train,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
2,9.025,1995,259.4092,0.060783,2603.0920,Train,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
3,11.800,1995,99.9830,0.065555,1101.7130,Train,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
4,NaN,1983,56.4402,0.248859,158.9402,Train,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,NaN,1983,136.5704,0.050505,NaN,Production,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
1701,21.300,2002,57.0744,0.041118,NaN,Production,0,0,0,0,...,0,0,1,0,0,0,1,0,1,0
1702,20.400,2005,182.7422,0.191273,NaN,Production,0,1,0,0,...,0,1,1,0,0,0,0,1,1,0
1703,20.000,2007,266.9672,0.013000,NaN,Production,0,0,1,0,...,0,1,0,1,0,1,0,0,0,1
1704,8.080,2000,238.7694,0.098982,NaN,Production,0,0,0,0,...,0,0,1,0,0,0,0,1,1,0

##### Imputing Counterfeit_weight missing values with mean from train dataset only

In [105]:
wgt_mean = round(full_data.loc[full_data['Data_from'] == 'Train','Counterfeit_Weight'].mean(),3)

In [106]:
wgt_mean

14.115

In [109]:
full_data['Counterfeit_Weight'].fillna(wgt_mean,inplace=True)

In [111]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8523 entries, 0 to 1704
Data columns (total 39 columns):
Counterfeit_Weight            8523 non-null float64
Active_Since                  8523 non-null int64
Medicine_MRP                  8523 non-null float64
Availability_rating           8523 non-null float64
Counterfeit_Sales             6818 non-null float64
Data_from                     8523 non-null object
DistID_Area013                8523 non-null uint8
DistID_Area017                8523 non-null uint8
DistID_Area018                8523 non-null uint8
DistID_Area019                8523 non-null uint8
DistID_Area027                8523 non-null uint8
DistID_Area035                8523 non-null uint8
DistID_Area045                8523 non-null uint8
DistID_Area046                8523 non-null uint8
DistID_Area049                8523 non-null uint8
MedType_Antacids              8523 non-null uint8
MedType_Antibiotics           8523 non-null uint8
MedType_Antifungal            8523 non-null uint8
MedType_Antimalarial          8523 non-null uint8
MedType_Antipyretics          8523 non-null uint8
MedType_Antiseptics           8523 non-null uint8
MedType_Antiviral             8523 non-null uint8
MedType_Cardiac               8523 non-null uint8
MedType_Hreplacements         8523 non-null uint8
MedType_Mstablizers           8523 non-null uint8
MedType_MuscleRelaxants       8523 non-null uint8
MedType_OralContraceptives    8523 non-null uint8
MedType_Statins               8523 non-null uint8
MedType_Stimulants            8523 non-null uint8
MedType_Tranquilizers         8523 non-null uint8
SidLvl_mild                   8523 non-null uint8
ArTyp_DownTown                8523 non-null uint8
ArTyp_Industrial              8523 non-null uint8
ArTyp_MidTownResidential      8523 non-null uint8
ArDisTyp_Medium               8523 non-null uint8
ArDisTyp_Small                8523 non-null uint8
ArDisTyp_Unknown              8523 non-null uint8
ArCtyTyp_Tier 2               8523 non-null uint8
ArCtyTyp_Tier 3               8523 non-null uint8
dtypes: float64(4), int64(1), object(1), uint8(33)
memory usage: 1.0+ MB

##### Now Saeperating data into Training and Production

In [115]:
training_data = full_data.loc[full_data['Data_from'] == 'Train']
training_data.drop('Data_from',axis=1,inplace=True)

In [116]:
training_data

,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,Counterfeit_Sales,DistID_Area013,DistID_Area017,DistID_Area018,DistID_Area019,DistID_Area027,...,MedType_Tranquilizers,SidLvl_mild,ArTyp_DownTown,ArTyp_Industrial,ArTyp_MidTownResidential,ArDisTyp_Medium,ArDisTyp_Small,ArDisTyp_Unknown,ArCtyTyp_Tier 2,ArCtyTyp_Tier 3
0,13.100,1995,160.2366,0.070422,1775.5026,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
1,14.115,1983,110.4384,0.013000,3069.1520,0,0,0,0,1,...,0,1,0,0,0,1,0,0,0,1
2,9.025,1995,259.4092,0.060783,2603.0920,0,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
3,11.800,1995,99.9830,0.065555,1101.7130,0,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
4,14.115,1983,56.4402,0.248859,158.9402,0,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6813,8.535,1995,204.1452,0.112963,2070.4520,0,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
6814,20.650,1995,235.1088,0.131103,2126.3792,0,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
6815,20.000,2005,193.6292,0.105096,2119.7212,0,1,0,0,0,...,0,0,1,0,0,0,0,1,1,0
6816,10.180,2000,162.8682,0.099957,1485.2138,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,0
6817,7.930,2007,177.5500,0.117445,1943.9500,0,0,1,0,0,...,0,0,0,1,0,1,0,0,0,1

In [121]:
production_data = full_data.loc[full_data['Data_from'] == 'Production']

In [122]:
production_data.drop(['Counterfeit_Sales','Data_from'],axis='columns',inplace=True)

In [123]:
production_data

,Counterfeit_Weight,Active_Since,Medicine_MRP,Availability_rating,DistID_Area013,DistID_Area017,DistID_Area018,DistID_Area019,DistID_Area027,DistID_Area035,...,MedType_Tranquilizers,SidLvl_mild,ArTyp_DownTown,ArTyp_Industrial,ArTyp_MidTownResidential,ArDisTyp_Medium,ArDisTyp_Small,ArDisTyp_Unknown,ArCtyTyp_Tier 2,ArCtyTyp_Tier 3
0,14.115,1983,85.5328,0.112747,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,1
1,13.450,2000,257.1460,0.144446,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,0
2,7.100,2000,98.1172,0.144221,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,0
3,18.300,1996,135.3730,0.100388,0,0,0,0,0,0,...,1,1,0,0,1,0,0,1,0,1
4,14.115,1983,112.8016,0.022585,0,0,0,1,0,0,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,14.115,1983,136.5704,0.050505,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,1
1701,21.300,2002,57.0744,0.041118,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,1,0
1702,20.400,2005,182.7422,0.191273,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,1,0
1703,20.000,2007,266.9672,0.013000,0,0,1,0,0,0,...,0,1,0,1,0,1,0,0,0,1
1704,8.080,2000,238.7694,0.098982,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,1,0